// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WPFW9.Migrations
{
    [DbContext(typeof(MijnContext))]
    partial class MijnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Boek", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.ToTable("Boeken");

                    b.HasData(
                        new
                        {
                            ISBN = "978-7-6512-7309-0",
                            Auteur = "Wade Dorota Kató",
                            Genre = "liefde",
                            Titel = "De grote liefde"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-1",
                            Auteur = "Josip Suse Dane",
                            Genre = "horror",
                            Titel = "De bloedende brie"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-2",
                            Auteur = "Genesio Nilüfer Ruzzier",
                            Genre = "actie",
                            Titel = "Schietende mensen"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-3",
                            Auteur = "CelestineKristaLambert",
                            Genre = "horror",
                            Titel = "De bloedende brie"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-4",
                            Auteur = "Eilert Farid Holmström",
                            Genre = "liefde",
                            Titel = "Pief paf poef"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-5",
                            Auteur = "Josip Suse Dane",
                            Genre = "horror",
                            Titel = "De uitgebloede brief"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-6",
                            Auteur = "Cosip Suse Dane",
                            Genre = "liefde",
                            Titel = "John en Emma"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-7",
                            Auteur = "CelestineKristaLambert",
                            Genre = "actie",
                            Titel = "De bloedende brie"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-8",
                            Auteur = "CelestineKristaLambert",
                            Genre = "actie",
                            Titel = "Het grote hart van John"
                        },
                        new
                        {
                            ISBN = "978-7-6512-7309-9",
                            Auteur = "AAAA",
                            Genre = "actie",
                            Titel = "DSchietende menseie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
